### PR TITLE
Pin python to <3.11

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/conda-forge/napari-feedstock/issues/45

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dstansby** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Hey, thanks for the submission! Unfortunately this won't be enough. This is best addressed in a repodata patch. Having a new build with restricted pins will not prevent the older versions from being installed. [Check previous PRs like this one](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/314).

**Review by jaimergp — CHANGES_REQUESTED** [review]
See comment above.

**Comment by dstansby** [comment]
👍 I'll close this, and open a new PR in the other feedstock, thanks for the quick reply!

**Pull request closed without merging**
