### PR TITLE
Do not add sphinx as a runtime dependency

### PR DESCRIPTION
**Pull request by hmaarrfk**
Would it be ok to remove sphinx from a runtime dependency?

The pinning is quite restrictive and I don't think it adds value to an end user that uses the napari GUI.

Thank you for considering

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
did it break something in napari or in numpydoc? 

it seems that numpydoc recommends greater than 4.2 and in the upcoming rc this was bumped to 5 with no particular notes of any issues 
https://github.com/numpy/numpydoc/pull/461


There is a mention of https://github.com/numpy/numpydoc/issues/399 but that was closed last year.

**Comment by hmaarrfk** [comment]
if help jogg the memory, it seems to "load" fine:
image

**Comment by psobolewskiPhD** [comment]
Here's some relevant discussion from zulip:
https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari.20sphinx.20dependency
I think the thought is to loosen the pins, rather than remove.

**Comment by hmaarrfk** [comment]
ok it seems that it is being worked on upstream. i'll be patient.

**Comment by jni** [comment]
Your timing was impeccable though @hmaarrfk! 😃

**Pull request closed without merging**
